### ISSUE TITLE
gitbook server Compile exception

### ISSUE THREAD

**Issue by zq99299** [PrismJS/prism#1084]
Previously, now do not know how to report the wrong
```
Administrator@USER-UHN4OVOOGF /F/笔记/gitbook/vue-note (master)
$ gitbook serve ./ --debug
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 16 plugins are installed
info: 14 explicitly listed
info: loading plugin "splitter"... OK
info: loading plugin "github"... OK
info: loading plugin "prism"... OK
info: loading plugin "expandable-chapters"... OK
info: loading plugin "anchors"... OK
info: loading plugin "anchor-navigation-ex"... OK
info: loading plugin "advanced-emoji"... OK
info: loading plugin "bootstrap-callout"... OK
info: loading plugin "livereload"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 8 pages
info: found 11 asset files
Failed to load prism syntax: javasrcipt
{ Error: Cannot find module 'prismjs/components/prism-javasrcipt.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.code (f:\笔记\gitbook\vue-note\node_modules\gitbook-plugin-prism\index.js:64:11)
    at Record.TemplateBlock.applyBlock (C:\Users\Administrator\.gitbook\versions\3.2.2\lib\models\templateBlock.js:205:23)
    at C:\Users\Administrator\.gitbook\versions\3.2.2\lib\output\getModifiers.js:56:33
    at C:\Users\Administrator\.gitbook\versions\3.2.2\lib\output\modifiers\highlightCode.js:47:24
    at C:\Users\Administrator\.gitbook\versions\3.2.2\lib\output\modifiers\editHTMLElement.js:11:16
    at C:\Users\Administrator\.gitbook\versions\3.2.2\lib\utils\promise.js:36:16 code: 'MODULE_NOT_FOUND' }
Failed to load prism syntax: javasrcipt
{ Error: Cannot find module 'prismjs/components/prism-javasrcipt.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.code (f:\笔记\gitbook\vue-note\node_modules\gitbook-plugin-prism\index.js:64:11)
    at Record.TemplateBlock.applyBlock (C:\Users\Administrator\.gitbook\versions\3.2.2\lib\models\templateBlock.js:205:23)
    at C:\Users\Administrator\.gitbook\versions\3.2.2\lib\output\getModifiers.js:56:33
    at C:\Users\Administrator\.gitbook\versions\3.2.2\lib\output\modifiers\highlightCode.js:47:24
    at C:\Users\Administrator\.gitbook\versions\3.2.2\lib\output\modifiers\editHTMLElement.js:11:16
    at C:\Users\Administrator\.gitbook\versions\3.2.2\lib\utils\promise.js:36:16 code: 'MODULE_NOT_FOUND' }
info: >> generation finished with success in 8.8s !

Starting server ...
Serving book on http://localhost:4000

```

**Comment by mAAdhaTTah** [comment]
> Error: Cannot find module 'prismjs/components/prism-javasrcipt.js'

You spelled Javascript wrong

**Comment by zq99299** [comment]
en en 的确错了。 不知道写错了需要格式化的语法 也会错误。
