### ISSUE TITLE
Cannot read property 'rest' of undefined when using bash language

### ISSUE THREAD

**Issue by theoscat** [PrismJS/prism#1129]
Hello,

I was trying to use this great projet but i keep getting this error :

```
[2017-04-20 17:46:49.682] [ERROR] prizmLogs - TypeError: Cannot read property 'rest' of undefined
    at Object.tokenize (C:\Sources\TCN\prizmLogs\node_modules\prismjs\prism.js:265:21)
    at Object.highlight (C:\Sources\TCN\prizmLogs\node_modules\prismjs\prism.js:256:18)
    at C:\Sources\TCN\prizmLogs\routes\logs.js:36:22
    at Layer.handle [as handle_request] (C:\Sources\TCN\prizmLogs\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Sources\TCN\prizmLogs\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Sources\TCN\prizmLogs\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Sources\TCN\prizmLogs\node_modules\express\lib\router\layer.js:95:5)
    at C:\Sources\TCN\prizmLogs\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Sources\TCN\prizmLogs\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Sources\TCN\prizmLogs\node_modules\express\lib\router\index.js:275:10)
```

I used your basic exemple : 

```
   const prism = require('prismjs
   let body = 'test';
    try{
        body = prism.highlight(body, prism.languages.bash);

    }catch(err){
        logger.error(err);
        body = err.message;
    }
```
Nothing too fancy as you can see.
Node version is 7.7.3 and npm version is 4.1.2.

Did i miss something ? like the fact that it's not compatible with node 7.7.3 or whatever ?

Theo

**Comment by mAAdhaTTah** [comment]
`prism.languages.bash` is probably undefined. When you require prismjs in node, you need to import the components: require('prismjs/components/bash') or whatever the exact path is.

**Comment by theoscat** [comment]
Thanks, it seems that i missed this information while reading the documentation.
It's working as expected now.

Theo

**Comment by pinheadmz** [comment]
I'm having this issue. `require('prismjs/components/bash')` isn't right either. I see a file at `node_modules/prismjs/components/prism-bash.js` ?

**Comment by mAAdhaTTah** [comment]
@pinheadmz Yeah, should be `prism-bash`, but you can use the new `loadLanguages` helper as well.

**Comment by pinheadmz** [comment]
hm, `Cannot find module 'prism-bash'`

I'm trying run this script: https://github.com/pinheadmz/bcoin-org.github.io/blob/piguide1/guide-generator.js

Which throws an error from this script: https://github.com/pinheadmz/bcoin-org.github.io/blob/piguide1/utils/createHTML.js

```
There was a problem:  TypeError: Cannot read property 'rest' of undefined
Please report this to https://github.com/chjj/marked.
    at Object.tokenize (/Users/pinhead/bcoin-org.github.io/node_modules/prismjs/prism.js:265:22)
    at Object.highlight (/Users/pinhead/bcoin-org.github.io/node_modules/prismjs/prism.js:256:18)
    at Renderer.renderer.code (/Users/pinhead/bcoin-org.github.io/utils/createHTML.js:66:22)
    at Parser.tok (/Users/pinhead/bcoin-org.github.io/node_modules/marked/lib/marked.js:999:28)
    at Parser.parse (/Users/pinhead/bcoin-org.github.io/node_modules/marked/lib/marked.js:944:17)
    at Function.Parser.parse (/Users/pinhead/bcoin-org.github.io/node_modules/marked/lib/marked.js:931:17)
    at marked (/Users/pinhead/bcoin-org.github.io/node_modules/marked/lib/marked.js:1252:19)
    at createHTML (/Users/pinhead/bcoin-org.github.io/utils/createHTML.js:81:18)
    at generatePages (/Users/pinhead/bcoin-org.github.io/utils/generatePages.js:45:11)
    at Object.<anonymous> (/Users/pinhead/bcoin-org.github.io/guide-generator.js:49:1)
```

**Comment by mAAdhaTTah** [comment]
This: `require('prismjs/components/bash')` -> `require('prismjs/components/prism-bash')`. I didn't type out the whole path.

**Comment by pinheadmz** [comment]
Still getting that same error. Node V8. Am I putting the new line in the right place?
```
const Prism = require('prismjs');                                                                                                                                         const PrismLanguages = require('prism-languages');                                                                                                                        const _ = require('underscore');                                                                                                                                          require('prismjs/components/prism-bash');                        
```
