### ISSUE TITLE
My new test is not working

### ISSUE THREAD

**Issue by davidgatti** [PrismJS/prism#1269]
I made a new test for the language that I added following the documentation page and looking at what others did before me. And so I have the following: 

- **file**: keyword_feature.test
- **inside**: tests > languages > csp

The `keyword_feature.test` file has the following content...

```
child-src

----------------------------------------------------

[
	["keyword", "child-src"]
]

----------------------------------------------------

Checks for all keywords.
```

When I run: `npm test -- --language=csp` I get the following...

```
  The token stream transformer
    ✓ should handle all kinds of simple transformations
    ✓ should handle nested structures
    ✓ should strip empty tokens
    ✓ should strip empty token tree branches
    ✓ should ignore all properties in tokens except value and content

  The language name parsing
    ✓ should use the last language as the main language if no language is specified
    ✓ should use the specified language as main language
    ✓ should throw an error if there are multiple main languages


  8 passing (31ms)



  Testing language 'csp'
    1) – should pass test case 'keyword_feature'


  0 passing (586ms)
  1 failing

  1) Testing language 'csp' – should pass test case 'keyword_feature':

      Uncaught AssertionError: Checks for all keywords.
Token Stream:
["child-src"]
-----------------------------------------
Expected Token Stream:
[["keyword","child-src"]]
-----------------------------------------
"child-src"]: expected [ 'child-src' ] to deeply equal [ [ 'keyword', 'child-src' ] ]
      + expected - actual

       [
      -  "child-src"
      +  [
      +    "keyword"
      +    "child-src"
      +  ]
       ]

      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:205:32)
      at Object.runTestCase (tests/helper/test-case.js:78:23)
      at process.<anonymous> (tests/run-child.js:12:15)
      at emit (internal/child_process.js:772:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

I'm not sure what I'm missing because if I look at the `comment_feature.test` than it seams that I'm doing everything right. What am I missing?

**Comment by davidgatti** [comment]
Never mind, I had a problem with the regexp. Sorry for bothering.
