### ISSUE TITLE
Greedy matching failing out of box on Ubuntu 18.04

### ISSUE THREAD

**Issue by bencoman** [PrismJS/prism#2040]
**Information:**
[npm-debug.log](https://github.com/PrismJS/prism/files/3572641/npm-debug.log)

- Prism version: latest HEAD
- Environment: Ubuntu 18.04 on Windows Subsystem for Linux 

This could easily be user-error.  I'm not a Javascript programmer and was hoping the following was sufficient to run the tests, but I get an error.  Only installed Ubuntu a few days ago so fairly clear of prerequisites - am I missing any? ) 
```
$ sudo apt-get install node.js npm mocha chai
$ git clone git@github.com:PrismJS/prism.git
$ cd prism
$ npm test

> prismjs@1.17.1 test /home/ben/Repo/prism
> npm run test:runner && npm run test:core && npm run test:languages && npm run test:plugins && npm run test:aliases && npm run test:pattern

> prismjs@1.17.1 test:runner /home/ben/Repo/prism
> mocha tests/testrunner-tests.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ben/Repo/prism/tests/testrunner-tests.js:3:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /usr/lib/nodejs/mocha/lib/mocha.js:172:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/usr/lib/nodejs/mocha/lib/mocha.js:169:14)
    at Mocha.run (/usr/lib/nodejs/mocha/lib/mocha.js:356:31)
    at Object.<anonymous> (/usr/lib/nodejs/mocha/bin/_mocha:366:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "test:runner"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! prismjs@1.17.1 test:runner: `mocha tests/testrunner-tests.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prismjs@1.17.1 test:runner script 'mocha tests/testrunner-tests.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prismjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha tests/testrunner-tests.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs prismjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls prismjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ben/Repo/prism/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by RunDevelopment** [comment]
> $ sudo apt-get install node.js npm mocha chai

No idea what these packages are supposed to be but I don't think they're the right ones and in the case mocha and chai, they are definitely not the right ones.

[Here](https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/)'s a guide on how to install NodeJS (I recommend 12). This will include `node` and `npm`. Unfortunately, apt-get alone won't give you a recent node version.

After that is installed do this:

```bash
git clone git@github.com:PrismJS/prism.git
cd prism
npm install
npm test
```

`npm install` will install all dependencies you need (e.g. mocha and chai).

Hope this helps.
