### ISSUE TITLE
ReferenceError: Prism is not defined after updating from 1.15 to 1.21

### ISSUE THREAD

**Issue by danez** [PrismJS/prism#2558]
**Information:**
- Prism version: 1.21.0
- Plugins: 'none'
- Environment: Browser, Node, Webpack

**Description**
```
ReferenceError: Prism is not defined
    at Object.<anonymous> (//node_modules/prismjs/components/prism-graphql.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (//component.js.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

**Example**

This code is used in webpack, but as well in nodejs:

```
import Prism from 'prismjs/components/prism-core';
import 'prismjs/components/prism-graphql';

...
```

In nodejs this results in error:
```
require('component.js`);
```

**Comment by mAAdhaTTah** [comment]
Do you have a reproducible example? I'm not sure I follow what the `require('component.js')` is/does and how that relates to the snippet above it.
